version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./server:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    links:
      - db
  db:
    build: ./docker/db
    ports:
      - "5432:5432"
    volumes:
      - cakephp_pgdatavol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrs
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - php
volumes:
  cakephp_pgdatavol:
